name: multi_crop_picker
description: instagrammable multi crop picker. this package do multiple image select, with ratio, length, grid(crossAxisCount), etc args. (crop featrue based on xclud/flutter_crop, gallery feture based on CaiJingLong/flutter_photo_manager)
repository: https://github.com/ukkoon/multi_crop_picker
version: 0.0.6
homepage: https://github.com/ukkoon/multi_crop_picker


environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^2.6.0
  provider: ^6.0.5
  collision: ^0.0.3
  vector_math: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter    
  flutter_lints: ^1.0.0  

flutter: